CREATE DATABASE IF NOT EXISTS restaurant_db;
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS product_db;
CREATE DATABASE IF NOT EXISTS cart_db;
CREATE DATABASE IF NOT EXISTS order_db;
CREATE DATABASE IF NOT EXISTS payment_db;

CREATE USER IF NOT EXISTS 'restaurant'@'%' IDENTIFIED BY 'restaurant123';
GRANT ALL PRIVILEGES ON *.* TO 'restaurant'@'%';
FLUSH PRIVILEGES;
